---
engine_version: 0.4.37
file_version: 2025-10-16 06:02:15.776852000 +02:00
resources:
- name: slot
  preferences:
    columns:
    - access_type: hidden
      name: starts_at
    - access_type: hidden
      name: ends_at
    - name: to_label
      display_name: Label
      column_type: string
      access_type: read_only
      virtual: true
      format: {}
      validators: []
      description: ''
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: day_of_week
    - access_type: hidden
      name: id
    display_column: to_label
    display_primary_key: false
  updated_at: 2025-10-16 08:02:15.776852000 +02:00
- name: user
  preferences:
    associations:
    - visible: false
      name: slots
  updated_at: 2025-10-16 07:56:14.736334000 +02:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2025-10-08 12:12:56.346248000 +02:00
- key: resources.slot.columns.order
  value:
  - id
  - to_label
  - max_participants
  - day_of_week
  - starts_at
  - ends_at
  - updated_at
  - created_at
  updated_at: 2025-10-08 15:00:32.901653000 +02:00
queries:
- id: 1
  name: First user
  sql_body: select name from users limit 1;
  description:
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
    api_config_name: origin
  tags: []
  updated_at: 2025-10-08 12:21:00.897097000 +02:00
dashboards: []
forms:
- id: 2
  name: New slot
  http_method: POST
  api_path: "/admin/api/data/slots"
  description:
  preferences:
    fields:
    - display_name: Day of week
      name: day_of_week
      field_type: number
      default_value: 1
      validators:
      - required: true
    - display_name: Starts at
      name: starts_at
      field_type: input
      default_value: ''
      validators:
      - required: true
      - format: "\\d\\d:\\d\\d"
        message: Format 00:00
      is_array: false
      conditions: []
    - display_name: Ends at
      name: ends_at
      field_type: input
      default_value: ''
      validators:
      - required: true
      - format: "\\d\\d:\\d\\d"
        message: Format 00:00
      is_array: false
    - display_name: Max participants
      name: max_participants
      field_type: number
      default_value: 4
      validators:
      - required: true
    request_type: rest
  api_config_name: origin
  tags: []
  updated_at: 2025-10-15 21:39:47.668031000 +02:00
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2025-10-08 12:12:56.348952000 +02:00
